[package]
name = "advent-of-code-2015"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day01"

[[bin]]
name = "day02"

[[bin]]
name = "day03"

[[bin]]
name = "day04"

[dependencies]
md5 = "0.7.0"
num_cpus = "1.14.0"
